type: vae
training:
  learning_rate: 1e-3
  weight_decay: 0.0001
  num_epochs: 5
  grad_clip: 1.0
  logdir: "logs/vae_training_r184"
  save_every: 1
  log_every: 10
  profile: false
data:
  image_size: 64
  num_classes: 1081
  batch_size: 128
  num_workers: 8
  augmentation_mode: "vae"
model:
  in_channels: 3
  latent_dim: 16
  depths:
    - 3
    - 5
    - 7
    - 3
  dims:
    - 48
    - 96
    - 192
    - 384
  ln_eps: 1e-6
  iaf: false
mlflow:
  experiment_name: "VAE_Training"
  tracking_uri: "file:./mlruns"